apiVersion: v1
kind: PersistentVolume
metadata:
  name: pidor-bot-pv
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /db_user
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2
